/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    //TASK 1 TEST+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @Test
    void Task1ReturnsZeroForEmptyElementList() {
        // Arrange
        SimpleFunctions funcs = new SimpleFunctions();
        List<Integer> a = new ArrayList<>();
        List<Integer> b = Arrays.asList(0, 1, 2);
        int expected = 0;

        // Act
        int result = funcs.Task1(a, b);

        // Assert
        assertEquals(expected, result, "Task1 should return 0 when the element list is empty.");
    }

    @Test
    void Task1HandlesNegativeIndexes() {
        // Arrange
        SimpleFunctions funcs = new SimpleFunctions();
        List<Integer> a = Arrays.asList(5, 10, 15);
        List<Integer> b = Arrays.asList(-1, 0, 1);
        int expected = 5 + 10;  // Index -1 is out-of-range and should be ignored

        // Act
        int result = funcs.Task1(a, b);

        // Assert
        assertEquals(expected, result, "Task1 should ignore negative indexes.");
    }
}
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
