/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //tests for Task4
    @Test void Task4AddsTwoNumbersfromTwoLists() {
        //arrange
        SimpleFunctions funcs = new SimpleFunctions();
        List<Integer> list1 = List.of(154, 343, 123, 234, 234);
        List<Integer> list2 = List.of(2, 4, 2, 4, 2);
        List<Integer> expected = List.of(308, 1372, 246, 936, 468);
        //act
        List<Integer> result = funcs.Task4(list1, list2);
        //assert
        assertEquals(expected, result);
    }

    @Test void Task4ReturnsNullIfListsAreNotEqual() {
        //arrange
        SimpleFunctions funcs = new SimpleFunctions();
        List<Integer> list1 = List.of(154, 343, 123, 234, 234);
        List<Integer> list2 = List.of(2, 4, 2, 4);
        //act
        List<Integer> result = funcs.Task4(list1, list2);
        //assert
        assertNull(result);
    }
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    // tests for task5

    @Test void Task5sortedListBoolTest(){
        //arrange
        SimpleFunctions funcs = new SimpleFunctions();
        List<Integer> list = List.of(123, 154, 234, 234, 343);
        Boolean expected = true;

        //act
        Boolean result = funcs.Task5(list);
        //assert
        assertEquals(expected, result);
    }
    @Test void Task5unsortedListBoolTest(){
        //arrange
        SimpleFunctions funcs = new SimpleFunctions();
        List<Integer> list = List.of(154, 343, 123, 234, 234);
        Boolean expected = false;
        //act
        Boolean result = funcs.Task5(list);
        //assert
        assertEquals(expected, result);
    }

    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

        // tests for Task6
    @Test 
    void Task6ReturnsEmptyListForEmptyInput() {
        // arrange
        SimpleFunctions funcs = new SimpleFunctions();
        List<Integer> input = new ArrayList<>();
        List<Integer> expected = new ArrayList<>();
        // act
        List<Integer> result = funcs.Task6(input);
        // assert
        assertEquals(expected, result);
    }
        @Test 
    void Task6ReturnsCorrectRoundedNumbers() {
        // arrange
        SimpleFunctions funcs = new SimpleFunctions();
        List<Integer> input = List.of(154, 343, 123, 234, 234);
        List<Integer> expected = List.of(200, 400, 200, 300, 300);
        // act
        List<Integer> result = funcs.Task6(input);
        // assert
        assertEquals(expected, result);
    }
   // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
}
