/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;

import java.util.Arrays;
import java.util.List;

public class App {
    public static void main(String[] args) {
        //TASK 6 Preliminary testing 
        /* 
        List<Integer> numbers = Arrays.asList( 100,150, 200, 275, 325);

        // Call the Task6 method from SimpleFunctions class
        List<Integer> roundedNumbers = SimpleFunctions.Task6(numbers);

        // Print the results
        System.out.println("original list: " + numbers);
        System.out.println("rounded numbers: " + roundedNumbers);
        */
    }
}
